# Generated by Django 5.0.6 on 2024-06-24 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_Producto', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre_Producto', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Carrito', models.IntegerField()),
                ('ID_Cantidad', models.IntegerField()),
                ('ID_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peludos.producto')),
            ],
        ),
    ]
