# Generated by Django 5.0.6 on 2024-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peludos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Usuario', models.CharField(max_length=30)),
                ('Contraseña', models.CharField(max_length=20)),
                ('Ciudad', models.CharField(max_length=15)),
                ('Region', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='ID_Cantidad',
            new_name='Cantidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
