# Generated by Django 5.0.6 on 2024-06-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peludos', '0002_usuario_rename_id_cantidad_carrito_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='ID_Carrito',
            new_name='IDCarrito',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='ID_Producto',
            new_name='IDProducto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='ID_Producto',
            new_name='IDProducto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre_Producto',
            new_name='NombreProducto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ID_usuario',
            new_name='IDUsuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre_Usuario',
            new_name='NombreUsuario',
        ),
    ]
