# Generated by Django 5.0.6 on 2024-06-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peludos', '0003_rename_id_carrito_carrito_idcarrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
